name: C++ Compile Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install g++ (if necessary)
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile part1.cpp and part2.cpp files
      run: |
        find . -name part1.cpp -exec g++ {} -o {}.o \;
        find . -name part2.cpp -exec g++ {} -o {}.o \;
